<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>jenkins-sonarqube-demo</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Jenkins SonarQube Maven Demo</name>
    <description>Simple Maven project for Jenkins and SonarQube integration</description>
    <distributionManagement>

    <repository>
        <id>nexus-releases</id>
        <name>maven-releases</name>
        <url>http://13.207.28.218:8081/repository/maven-releases/</url>
    </repository>

    </distributionManagement>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sonar.projectKey>jenkins-sonarqube-demo</sonar.projectKey>
        <sonar.projectName>Jenkins SonarQube Maven Demo</sonar.projectName>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
    <plugins>

        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-deploy-plugin</artifactId>
            <version>3.1.4</version>
        </plugin>

    </plugins>
</build>
</project>
